## Iris Dataset

In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [16]:
df = pd.read_csv("iris.csv")
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [18]:
X = df.drop('species', axis=1)
y = df['species']

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [20]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [21]:
X_train

array([[-1.47393679,  1.22037928, -1.5639872 , -1.30948358],
       [-0.13307079,  3.02001693, -1.27728011, -1.04292204],
       [ 1.08589829,  0.09560575,  0.38562104,  0.28988568],
       [-1.23014297,  0.77046987, -1.21993869, -1.30948358],
       [-1.7177306 ,  0.32056046, -1.39196294, -1.30948358],
       [ 0.59831066, -1.25412249,  0.72966956,  0.95628954],
       [ 0.72020757,  0.32056046,  0.44296246,  0.42316645],
       [-0.74255534,  0.99542457, -1.27728011, -1.30948358],
       [-0.98634915,  1.22037928, -1.33462153, -1.30948358],
       [-0.74255534,  2.34515281, -1.27728011, -1.44276436],
       [-0.01117388, -0.80421307,  0.78701097,  0.95628954],
       [ 0.23261993,  0.77046987,  0.44296246,  0.55644722],
       [ 1.08589829,  0.09560575,  0.5576453 ,  0.42316645],
       [-0.49876152,  1.8952434 , -1.39196294, -1.04292204],
       [-0.49876152,  1.44533399, -1.27728011, -1.30948358],
       [-0.37686461, -1.47907719, -0.01576889, -0.24323741],
       [ 0.59831066, -0.57925837,  0.78701097,  0.42316645],
       [ 0.72020757,  0.09560575,  1.01637665,  0.82300877],
       [ 0.96400139, -0.12934896,  0.38562104,  0.28988568],
       [ 1.69538284,  1.22037928,  1.36042516,  1.75597417],
       [-0.13307079, -0.35430366,  0.2709382 ,  0.15660491],
       [ 2.18297047, -0.12934896,  1.64713226,  1.22285108],
       [-0.2549677 , -0.12934896,  0.44296246,  0.42316645],
       [-0.86445224,  0.99542457, -1.33462153, -1.30948358],
       [ 2.30486738, -0.57925837,  1.70447368,  1.08957031],
       [-0.01117388, -0.80421307,  0.21359679, -0.24323741],
       [-0.74255534,  0.77046987, -1.33462153, -1.30948358],
       [-0.98634915,  0.99542457, -1.39196294, -1.17620281],
       [-0.86445224,  1.67028869, -1.04791443, -1.04292204],
       [-0.98634915, -2.37889602, -0.13045173, -0.24323741],
       [ 0.59831066, -0.80421307,  0.67232814,  0.82300877],
       [-1.23014297,  0.77046987, -1.04791443, -1.30948358],
       [-0.98634915, -0.12934896, -1.21993869, -1.30948358],
       [-0.86445224,  0.54551516, -1.16259727, -0.90964127],
       [-0.2549677 , -0.80421307,  0.2709382 ,  0.15660491],
       [-0.86445224,  0.77046987, -1.27728011, -1.30948358],
       [-0.13307079, -0.12934896,  0.2709382 ,  0.02332414],
       [ 2.30486738,  1.67028869,  1.70447368,  1.35613185],
       [-1.47393679,  0.32056046, -1.33462153, -1.30948358],
       [ 0.47641375, -0.35430366,  0.32827962,  0.15660491],
       [-0.13307079, -1.25412249,  0.72966956,  1.08957031],
       [-0.37686461,  2.57010752, -1.33462153, -1.30948358],
       [ 0.23261993, -0.12934896,  0.61498672,  0.82300877],
       [-0.01117388, -0.80421307,  0.78701097,  0.95628954],
       [ 0.23261993, -1.9289866 ,  0.15625537, -0.24323741],
       [-0.49876152, -0.12934896,  0.44296246,  0.42316645],
       [ 0.47641375,  0.77046987,  0.95903523,  1.48941263],
       [-0.37686461, -1.7040319 ,  0.15625537,  0.15660491],
       [-0.49876152,  1.8952434 , -1.16259727, -1.04292204],
       [-0.98634915, -1.7040319 , -0.24513457, -0.24323741],
       [ 0.72020757, -0.80421307,  0.90169381,  0.95628954],
       [-0.98634915,  0.54551516, -1.33462153, -1.30948358],
       [-0.98634915,  0.32056046, -1.44930436, -1.30948358],
       [-0.37686461, -1.47907719,  0.04157253, -0.10995664],
       [ 1.08589829, -0.12934896,  0.72966956,  0.68972799],
       [-1.10824606,  0.09560575, -1.27728011, -1.44276436],
       [-0.01117388, -0.57925837,  0.78701097,  1.6226934 ],
       [-0.98634915,  0.77046987, -1.27728011, -1.30948358],
       [-0.98634915,  0.99542457, -1.21993869, -0.7763605 ],
       [ 0.11072303,  0.32056046,  0.61498672,  0.82300877],
       [-0.86445224, -1.25412249, -0.41715882, -0.10995664],
       [ 1.32969211,  0.32056046,  1.13105949,  1.48941263],
       [ 0.23261993, -0.80421307,  0.78701097,  0.55644722],
       [ 0.35451684, -1.02916778,  1.07371807,  0.28988568],
       [ 2.30486738, -0.12934896,  1.36042516,  1.48941263],
       [-0.37686461, -1.25412249,  0.15625537,  0.15660491],
       [-1.7177306 , -0.35430366, -1.33462153, -1.30948358],
       [-1.83962751, -0.12934896, -1.50664578, -1.44276436],
       [ 0.23261993, -1.9289866 ,  0.72966956,  0.42316645],
       [ 1.69538284,  0.32056046,  1.30308374,  0.82300877],
       [-1.47393679,  0.09560575, -1.27728011, -1.30948358],
       [-0.86445224,  0.99542457, -1.33462153, -1.17620281],
       [-1.7177306 , -0.12934896, -1.39196294, -1.30948358],
       [ 0.59831066, -1.25412249,  0.67232814,  0.42316645],
       [ 0.59831066,  0.77046987,  1.07371807,  1.6226934 ],
       [-1.47393679,  0.77046987, -1.33462153, -1.17620281],
       [ 1.2077952 , -0.12934896,  1.01637665,  1.22285108],
       [ 0.59831066,  0.54551516,  1.30308374,  1.75597417],
       [-1.35203988,  0.32056046, -1.39196294, -1.30948358],
       [ 0.35451684, -0.35430366,  0.5576453 ,  0.28988568],
       [ 0.84210448, -0.57925837,  0.50030388,  0.42316645],
       [ 0.47641375, -0.57925837,  0.61498672,  0.82300877],
       [ 1.45158902,  0.32056046,  0.5576453 ,  0.28988568],
       [ 0.72020757,  0.32056046,  0.90169381,  1.48941263],
       [-0.86445224,  1.67028869, -1.21993869, -1.30948358],
       [ 1.32969211,  0.09560575,  0.95903523,  1.22285108],
       [ 0.11072303, -0.12934896,  0.2709382 ,  0.42316645],
       [ 0.84210448, -0.12934896,  0.84435239,  1.08957031],
       [-0.13307079, -1.02916778, -0.13045173, -0.24323741],
       [-0.74255534, -0.80421307,  0.09891395,  0.28988568],
       [ 0.35451684, -0.12934896,  0.50030388,  0.28988568],
       [-1.5958337 , -1.7040319 , -1.39196294, -1.17620281],
       [ 0.96400139, -0.35430366,  0.50030388,  0.15660491],
       [-0.37686461, -1.02916778,  0.38562104,  0.02332414],
       [-0.62065843,  1.44533399, -1.27728011, -1.30948358],
       [-0.2549677 , -0.12934896,  0.21359679,  0.15660491],
       [ 1.81727975, -0.35430366,  1.475108  ,  0.82300877],
       [ 1.08589829,  0.54551516,  1.13105949,  1.22285108],
       [-0.86445224,  1.44533399, -1.27728011, -1.04292204],
       [-1.10824606, -1.47907719, -0.24513457, -0.24323741],
       [ 1.08589829,  0.54551516,  1.13105949,  1.75597417],
       [ 1.69538284, -0.12934896,  1.18840091,  0.55644722],
       [-1.10824606,  0.09560575, -1.27728011, -1.44276436],
       [ 1.08589829,  0.09560575,  1.07371807,  1.6226934 ],
       [-1.10824606, -0.12934896, -1.33462153, -1.30948358],
       [ 1.32969211,  0.09560575,  0.67232814,  0.42316645],
       [ 1.93917666, -0.57925837,  1.36042516,  0.95628954],
       [ 0.59831066, -0.35430366,  1.07371807,  0.82300877],
       [-0.13307079, -0.57925837,  0.21359679,  0.15660491],
       [ 0.84210448, -0.12934896,  1.01637665,  0.82300877],
       [ 0.59831066, -1.7040319 ,  0.38562104,  0.15660491],
       [ 0.72020757, -0.35430366,  0.32827962,  0.15660491],
       [-0.2549677 , -0.57925837,  0.67232814,  1.08957031],
       [ 0.11072303, -0.12934896,  0.78701097,  0.82300877],
       [-0.49876152,  0.77046987, -1.16259727, -1.30948358],
       [ 0.35451684, -0.57925837,  0.15625537,  0.15660491],
       [-1.10824606, -1.25412249,  0.44296246,  0.68972799],
       [-0.01117388,  2.1201981 , -1.44930436, -1.30948358],
       [-0.01117388, -1.02916778,  0.15625537,  0.02332414],
       [ 1.57348593, -0.12934896,  1.24574233,  1.22285108]])

In [22]:
model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [23]:
y_pred = model.predict(X_test)

In [24]:
accuracy = accuracy_score(y_test, y_pred)
print("Model Accuracy:", accuracy)

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:", cm)

print(classification_report(y_test, y_pred))

Model Accuracy: 1.0
Confusion Matrix: [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Diabetes

In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [26]:
df = pd.read_csv("diabetes.csv")
df.head()

   Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [27]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [28]:
X = df.drop("Outcome", axis=1)
y = df["Outcome"]

In [29]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [30]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [32]:
model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [33]:
y_pred = model.predict(X_test)

In [34]:
accuracy = accuracy_score(y_test, y_pred)
print("Model Accuracy:", accuracy)

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:", cm)

print(classification_report(y_test, y_pred))

Model Accuracy: 0.7077922077922078
Confusion Matrix: [[81 18]
 [27 28]]
              precision    recall  f1-score   support

           0       0.75      0.82      0.78        99
           1       0.61      0.51      0.55        55

    accuracy                           0.71       154
   macro avg       0.68      0.66      0.67       154
weighted avg       0.70      0.71      0.70       154

### Heart

In [35]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [36]:
df = pd.read_csv("heart.csv")
df.head()

   age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [37]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [38]:
X = df.drop("target", axis=1)
y = df['target']

In [39]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [40]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [48]:
scores = []

for k in range(1, 6):
  model = KNeighborsClassifier(n_neighbors=k)
  model.fit(X_train, y_train)
  y_pred = model.predict(X_test)
  accuracy = accuracy_score(y_test, y_pred)
  scores.append(accuracy)

In [49]:
best_k = scores.index(max(scores)) + 1
print("Best k : ", best_k)

Best k :  5

In [50]:
model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train, y_train)

KNeighborsClassifier()

In [51]:
y_pred = model.predict(X_test)

In [52]:
accuracy = accuracy_score(y_test, y_pred)
print("Model Accuracy:", accuracy)

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:", cm)

print(classification_report(y_test, y_pred))

Model Accuracy: 0.9016393442622951
Confusion Matrix: [[27  2]
 [ 4 28]]
              precision    recall  f1-score   support

           0       0.87      0.93      0.90        29
           1       0.93      0.88      0.90        32

    accuracy                           0.90        61
   macro avg       0.90      0.90      0.90        61
weighted avg       0.90      0.90      0.90        61